services:
  - type: web
    name: osqr-interns-todo-app
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
